# -*- coding: utf-8 -*-
"""crop_recc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rf2E4z6zQ5flBg49_zcYscWv25hGEDUD
"""
import pickle
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv("C:\Anjali\python\projects\crop recc\dataset\Crop_recommendation.csv")


data.head()

data.shape

data.isnull().sum()


x=data.iloc[:,:-1]
y=data.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train.head()

y_train.head()

model=RandomForestClassifier()

model.fit(x_train,y_train)

pickle.dump(model,open("model.pkl","wb"))

predictions=model.predict(x_test)


accuracy=model.score(x_test,y_test)
print(accuracy)

new_features=[[36,58,25,28.66024,59,31891,36.9263]]
predicted_crop=model.predict(new_features)
print("Predicted crop:",predicted_crop)

